@switch(session('register_step'))
    @case(1)
        @include('register.register_1')
        @break
    @case(2)
        @include('register.register_2')
        @break
    @case(3)
        @include('register.register_3')
        @break
    @default
        @include('register.register_1')
@endswitch